package soroauth

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/stellar/go-stellar-sdk/keypair"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// referenceSDK is the exact reference build the vectors must come from. A
// vector recorded by any other version is not evidence about this one, so the
// test refuses it rather than comparing against it.
const referenceSDK = "@stellar/stellar-sdk@17.1.0"

// vectorStep is one signing call to make, in order.
type vectorStep struct {
	SignerLabel string  `json:"signer_label"`
	ForAddress  *string `json:"for_address"`
}

// vectorDelegate is one node of the delegate tree a vector was built from,
// recorded in the exact order it was passed to the JS SDK, before any sorting.
type vectorDelegate struct {
	Label   string           `json:"label"`
	Address string           `json:"address"`
	Nested  []vectorDelegate `json:"nested"`
}

// vector is one golden case, as written by testdata/gen/gen.mjs.
type vector struct {
	SchemaVersion     int              `json:"schema_version"`
	Name              string           `json:"name"`
	SDK               string           `json:"sdk"`
	NetworkPassphrase string           `json:"network_passphrase"`
	ValidUntilLedger  uint32           `json:"valid_until_ledger"`
	PreWrapEntryXDR   string           `json:"pre_wrap_entry_xdr"`
	UnsignedEntryXDR  string           `json:"unsigned_entry_xdr"`
	Delegates         []vectorDelegate `json:"delegates"`
	Steps             []vectorStep     `json:"steps"`
	PreimageXDR       string           `json:"preimage_xdr"`
	PayloadHex        string           `json:"payload_hex"`
	SignedEntryXDR    string           `json:"signed_entry_xdr"`
}

func loadVectors(t *testing.T) []vector {
	t.Helper()

	paths, err := filepath.Glob(filepath.Join("testdata", "vectors", "*.json"))
	if err != nil {
		t.Fatalf("globbing the vector directory: %v", err)
	}
	// Without this, deleting every vector would turn this file into a test
	// that passes by doing nothing.
	if len(paths) == 0 {
		t.Fatal("no golden vectors found in testdata/vectors; run `cd testdata/gen && npm ci && node gen.mjs`")
	}

	vectors := make([]vector, 0, len(paths))
	for _, path := range paths {
		raw, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("reading %s: %v", path, err)
		}
		var v vector
		// Unknown fields are rejected so a schema change cannot be silently
		// half-ignored by this side.
		decoder := json.NewDecoder(bytes.NewReader(raw))
		decoder.DisallowUnknownFields()
		if err := decoder.Decode(&v); err != nil {
			t.Fatalf("decoding %s: %v", path, err)
		}
		if v.SchemaVersion != 1 {
			t.Fatalf("%s has unsupported schema version %d, want 1", path, v.SchemaVersion)
		}
		if v.Name == "" {
			t.Fatalf("%s has no name", path)
		}
		if v.SDK != referenceSDK {
			t.Fatalf("%s was generated by %q, want %q", path, v.SDK, referenceSDK)
		}
		vectors = append(vectors, v)
	}
	return vectors
}

// toDelegates converts a recorded delegate tree into the library's own type,
// preserving the recorded order exactly. Preserving it is the point: the tree
// is recorded unsorted, so passing it through unchanged is what proves Go
// sorts it into the same shape the JS SDK did.
func toDelegates(recorded []vectorDelegate) []Delegate {
	if len(recorded) == 0 {
		return nil
	}
	out := make([]Delegate, 0, len(recorded))
	for _, node := range recorded {
		out = append(out, Delegate{
			Address: node.Address,
			Nested:  toDelegates(node.Nested),
		})
	}
	return out
}

// signerForLabel derives the vector's signing key from its label, the same way
// testdata/gen/gen.mjs does.
func signerForLabel(t *testing.T, label string) Signer {
	t.Helper()
	kp, err := keypair.FromRawSeed(sha256.Sum256([]byte(label)))
	if err != nil {
		t.Fatalf("deriving the keypair for %q: %v", label, err)
	}
	return NewEd25519Signer(kp)
}

// TestGoldenVectors is the correctness gate: for every recorded case, the
// preimage, the payload hash and the final signed entry must match the JS
// reference implementation byte for byte. Source-account entries pass
// through unchanged, so they are checked differently.
func TestGoldenVectors(t *testing.T) {
	for _, v := range loadVectors(t) {
		t.Run(v.Name, func(t *testing.T) {
			var entry xdr.SorobanAuthorizationEntry
			if err := xdr.SafeUnmarshalBase64(v.UnsignedEntryXDR, &entry); err != nil {
				t.Fatalf("decoding the unsigned entry: %v", err)
			}

			// Source-account entries pass through unchanged.
			// Preimage returns ErrSourceAccountCredentials for this arm,
			// and the signed entry must be byte-identical to the unsigned
			// entry.
			if entry.Credentials.Type == xdr.SorobanCredentialsTypeSorobanCredentialsSourceAccount {
				// Verify the entry is byte-identical before and after.
				wantUnsigned, err := base64.StdEncoding.DecodeString(v.UnsignedEntryXDR)
				if err != nil {
					t.Fatalf("decoding the expected unsigned entry: %v", err)
				}
				gotSigned, err := entry.MarshalBinary()
				if err != nil {
					t.Fatalf("marshalling the entry: %v", err)
				}
				if !equalBytes(gotSigned, wantUnsigned) {
					t.Errorf("source-account entry was mutated\n before %x\n  after %x", wantUnsigned, gotSigned)
				}
				// Also verify AuthorizeEntry returns a copy that is
				// byte-identical (the pass-through behavior).
				// For source-account vectors, the signer is always SIGNER_1.
				copied, err := AuthorizeEntry(context.Background(), entry,
					signerForLabel(t, "soroauth-vector-signer-1"),
					v.ValidUntilLedger, v.NetworkPassphrase)
				if err != nil {
					t.Fatalf("AuthorizeEntry returned an unexpected error for source-account: %v", err)
				}
				gotCopied, err := copied.MarshalBinary()
				if err != nil {
					t.Fatalf("marshalling the copied entry: %v", err)
				}
				if !equalBytes(gotCopied, wantUnsigned) {
					t.Errorf("AuthorizeEntry changed a source-account entry\n want %x\n  got %x", wantUnsigned, gotCopied)
				}
				return
			}

			// 0. the wrap itself, for vectors that record a pre-wrap entry.
			// Without this the delegate vectors would only prove that Go can
			// re-read an entry JS already built; this proves Go builds the
			// same bytes from the same unsorted input.
			if v.PreWrapEntryXDR != "" {
				wantUnsigned, err := base64.StdEncoding.DecodeString(v.UnsignedEntryXDR)
				if err != nil {
					t.Fatalf("decoding the expected unsigned entry: %v", err)
				}

				var preWrap xdr.SorobanAuthorizationEntry
				if err := xdr.SafeUnmarshalBase64(v.PreWrapEntryXDR, &preWrap); err != nil {
					t.Fatalf("decoding the pre-wrap entry: %v", err)
				}

				wrapped, err := WithDelegates(preWrap, v.ValidUntilLedger, toDelegates(v.Delegates), nil)
				if err != nil {
					t.Fatalf("WithDelegates returned an unexpected error: %v", err)
				}
				gotWrapped, err := wrapped.MarshalBinary()
				if err != nil {
					t.Fatalf("marshalling the wrapped entry: %v", err)
				}
				if !equalBytes(gotWrapped, wantUnsigned) {
					t.Errorf("WithDelegates differs from buildWithDelegatesEntry\n want %x\n  got %x",
						wantUnsigned, gotWrapped)
				}
			}

			// 1. the preimage
			preimage, err := Preimage(entry, v.ValidUntilLedger, v.NetworkPassphrase)
			if err != nil {
				t.Fatalf("Preimage returned an unexpected error: %v", err)
			}
			gotPreimage, err := preimage.MarshalBinary()
			if err != nil {
				t.Fatalf("marshalling the preimage: %v", err)
			}
			wantPreimage, err := base64.StdEncoding.DecodeString(v.PreimageXDR)
			if err != nil {
				t.Fatalf("decoding the expected preimage: %v", err)
			}
			if !equalBytes(gotPreimage, wantPreimage) {
				t.Errorf("preimage differs from the reference\n want %x\n  got %x", wantPreimage, gotPreimage)
			}

			// 2. the payload hash
			payload, err := Payload(preimage)
			if err != nil {
				t.Fatalf("Payload returned an unexpected error: %v", err)
			}
			if got := hex.EncodeToString(payload[:]); got != v.PayloadHex {
				t.Errorf("payload differs from the reference\n want %s\n  got %s", v.PayloadHex, got)
			}

			// 3. the signed entry, after replaying every signing step
			signed := entry
			for i, step := range v.Steps {
				var opts []AuthorizeOption
				if step.ForAddress != nil {
					opts = append(opts, ForAddress(*step.ForAddress))
				}
				signed, err = AuthorizeEntry(context.Background(), signed,
					signerForLabel(t, step.SignerLabel),
					v.ValidUntilLedger, v.NetworkPassphrase, opts...)
				if err != nil {
					t.Fatalf("step %d (%s) returned an unexpected error: %v", i, step.SignerLabel, err)
				}
			}

			gotSigned, err := signed.MarshalBinary()
			if err != nil {
				t.Fatalf("marshalling the signed entry: %v", err)
			}
			wantSigned, err := base64.StdEncoding.DecodeString(v.SignedEntryXDR)
			if err != nil {
				t.Fatalf("decoding the expected signed entry: %v", err)
			}
			if !equalBytes(gotSigned, wantSigned) {
				t.Errorf("signed entry differs from the reference\n want %x\n  got %x", wantSigned, gotSigned)
			}
		})
	}
}

// TestGoldenVectorsCoverTheRequiredCases guards the set itself: a vector that
// is deleted, or never generated, must fail the build rather than quietly
// shrink the gate.
func TestGoldenVectorsCoverTheRequiredCases(t *testing.T) {
	required := []string{
		"legacy_single_testnet", // §5.9 case 1
		"legacy_single_public",  // §5.9 case 2
		"v2_single_testnet",     // §5.9 case 3
		"v2_sub_invocations",    // §5.9 case 4
		"v2_create_contract",    // §5.9 case 5
		"legacy_negative_nonce", // §5.9 case 9

		"delegates_unsorted_with_nested",    // §5.9 case 6
		"delegates_same_address_two_levels", // §5.9 case 7
		"delegates_from_legacy",             // §5.9 case 8

		"source_account_testnet", // #115: source-account pass-through
		"source_account_public",  // #115: source-account on public network

		"v2_expiration_boundary_1",   // #116: minimum valid expiration
		"v2_expiration_boundary_max", // #116: near-maximum expiration
	}

	present := map[string]bool{}
	for _, v := range loadVectors(t) {
		present[v.Name] = true
	}
	for _, name := range required {
		if !present[name] {
			t.Errorf("required golden vector %q is missing", name)
		}
	}
}

// TestGoldenPayloadsAreDistinct checks the separations §5.9 calls for, using
// the recorded payloads rather than recomputing them.
func TestGoldenPayloadsAreDistinct(t *testing.T) {
	payloads := map[string]string{}
	for _, v := range loadVectors(t) {
		payloads[v.Name] = v.PayloadHex
	}

	pairs := []struct {
		a, b   string
		reason string
	}{
		{
			a: "legacy_single_testnet", b: "legacy_single_public",
			reason: "a signature must not replay from testnet onto the public network",
		},
		{
			a: "legacy_single_testnet", b: "v2_single_testnet",
			reason: "V2 binds the address into the payload, so it must differ from legacy",
		},
		{
			a: "legacy_single_testnet", b: "legacy_negative_nonce",
			reason: "the nonce is what makes a signature single-use",
		},
		{
			a: "v2_single_testnet", b: "v2_expiration_boundary_1",
			reason: "different expiration produces a different payload",
		},
		{
			a: "v2_single_testnet", b: "v2_expiration_boundary_max",
			reason: "different expiration produces a different payload",
		},
		{
			a: "v2_expiration_boundary_1", b: "v2_expiration_boundary_max",
			reason: "boundary expirations must differ from each other",
		},
	}

	for _, pair := range pairs {
		t.Run(pair.a+" vs "+pair.b, func(t *testing.T) {
			first, second := payloads[pair.a], payloads[pair.b]
			if first == "" || second == "" {
				t.Skipf("one of the vectors is missing (%q, %q)", pair.a, pair.b)
			}
			if first == second {
				t.Errorf("payloads collided (%s); %s", first, pair.reason)
			}
		})
	}
}

// TestGoldenSourceAccountPassThrough asserts that source-account
// entries are byte-identical after AuthorizeEntry and AuthorizeAll,
// covering #115.
func TestGoldenSourceAccountPassThrough(t *testing.T) {
	for _, name := range []string{"source_account_testnet", "source_account_public"} {
		t.Run(name, func(t *testing.T) {
			v := findVector(t, name)
			var entry xdr.SorobanAuthorizationEntry
			if err := xdr.SafeUnmarshalBase64(v.UnsignedEntryXDR, &entry); err != nil {
				t.Fatalf("decoding the unsigned entry: %v", err)
			}

			before, err := entry.MarshalBinary()
			if err != nil {
				t.Fatalf("marshalling: %v", err)
			}

			signed, err := AuthorizeEntry(context.Background(), entry,
				signerForLabel(t, "soroauth-vector-signer-1"),
				v.ValidUntilLedger, v.NetworkPassphrase)
			if err != nil {
				t.Fatalf("AuthorizeEntry returned an unexpected error: %v", err)
			}

			after, err := signed.MarshalBinary()
			if err != nil {
				t.Fatalf("marshalling: %v", err)
			}
			if !equalBytes(before, after) {
				t.Errorf("AuthorizeEntry changed a source-account entry\n before %x\n  after %x", before, after)
			}

			// Also verify AuthorizeAll leaves it unchanged.
			allSigned, err := AuthorizeAll(context.Background(),
				[]xdr.SorobanAuthorizationEntry{entry},
				[]Signer{NewEd25519Signer(testKeypair(t, "soroauth-vector-signer-1"))},
				v.ValidUntilLedger, v.NetworkPassphrase)
			if err != nil {
				t.Fatalf("AuthorizeAll returned an unexpected error: %v", err)
			}
			allBefore, err := entry.MarshalBinary()
			if err != nil {
				t.Fatalf("re-marshalling: %v", err)
			}
			allAfter, err := allSigned[0].MarshalBinary()
			if err != nil {
				t.Fatalf("marshalling the all-signed entry: %v", err)
			}
			if !equalBytes(allBefore, allAfter) {
				t.Errorf("AuthorizeAll changed a source-account entry\n before %x\n  after %x", allBefore, allAfter)
			}
		})
	}
}

// TestGoldenExpirationBoundaries asserts that the expiration boundary
// vectors (#116) have the correct valid_until_ledger values and that
// their payloads differ from the standard-case vectors.
func TestGoldenExpirationBoundaries(t *testing.T) {
	for _, name := range []string{"v2_expiration_boundary_1", "v2_expiration_boundary_max"} {
		t.Run(name, func(t *testing.T) {
			v := findVector(t, name)
			if name == "v2_expiration_boundary_1" && v.ValidUntilLedger != 1 {
				t.Errorf("valid_until_ledger = %d, want 1", v.ValidUntilLedger)
			}
			if name == "v2_expiration_boundary_max" && v.ValidUntilLedger != 4294967295 {
				t.Errorf("valid_until_ledger = %d, want 4294967295", v.ValidUntilLedger)
			}
			// The signed entry must differ from the unsigned entry
			// since it now carries a signature.
			unsignedBytes, err := base64.StdEncoding.DecodeString(v.UnsignedEntryXDR)
			if err != nil {
				t.Fatalf("decoding unsigned entry: %v", err)
			}
			signedBytes, err := base64.StdEncoding.DecodeString(v.SignedEntryXDR)
			if err != nil {
				t.Fatalf("decoding signed entry: %v", err)
			}
			if equalBytes(unsignedBytes, signedBytes) {
				t.Errorf("the signed entry is byte-identical to the unsigned entry")
			}
		})
	}
}

// findVector finds a vector by name, or fatals.
func findVector(t *testing.T, name string) vector {
	t.Helper()
	for _, v := range loadVectors(t) {
		if v.Name == name {
			return v
		}
	}
	t.Fatalf("golden vector %q is missing", name)
	return vector{}
}

// equalBytes is bytes.Equal, named here so the golden assertions read as
// byte-for-byte comparisons.
func equalBytes(a, b []byte) bool { return bytes.Equal(a, b) }

// TestGoldenVectorSignsOneAddressAtTwoLevelsInOneStep pins §5.9 case 7 down
// precisely: the vector must contain one address at two nesting depths, and
// exactly ONE recorded signing step must fill both nodes. If a second step were
// ever added to make the byte comparison pass, this test fails — the whole
// point of the case is that one call covers both, because under CAP-71-01 both
// nodes commit to the same payload.
func TestGoldenVectorSignsOneAddressAtTwoLevelsInOneStep(t *testing.T) {
	const name = "delegates_same_address_two_levels"

	var found *vector
	for _, v := range loadVectors(t) {
		if v.Name == name {
			candidate := v
			found = &candidate
			break
		}
	}
	if found == nil {
		t.Fatalf("golden vector %q is missing", name)
	}

	if len(found.Steps) != 1 {
		t.Fatalf("the vector records %d signing steps, want exactly 1", len(found.Steps))
	}
	step := found.Steps[0]
	if step.ForAddress == nil {
		t.Fatal("the step does not name a target address")
	}

	var entry xdr.SorobanAuthorizationEntry
	if err := xdr.SafeUnmarshalBase64(found.UnsignedEntryXDR, &entry); err != nil {
		t.Fatalf("decoding the unsigned entry: %v", err)
	}

	target, err := ParseAddress(*step.ForAddress)
	if err != nil {
		t.Fatalf("parsing the target address: %v", err)
	}
	targetEncoded, err := addressBytes(target)
	if err != nil {
		t.Fatalf("encoding the target address: %v", err)
	}

	countMatching := func(e xdr.SorobanAuthorizationEntry) (total, signed int) {
		nodes, err := credentialNodes(&e)
		if err != nil {
			t.Fatalf("walking the entry: %v", err)
		}
		for _, node := range nodes {
			if bytes.Equal(node.encoded, targetEncoded) {
				total++
				if isSigned(*node.signature) {
					signed++
				}
			}
		}
		return total, signed
	}

	total, alreadySigned := countMatching(entry)
	if total != 2 {
		t.Fatalf("the address appears at %d nodes in the unsigned entry, want 2", total)
	}
	if alreadySigned != 0 {
		t.Fatalf("%d nodes are already signed in the unsigned entry, want 0", alreadySigned)
	}

	// Depth must genuinely differ, or "two nodes" would just be a duplicate at
	// one level, which CAP-71-01 forbids anyway.
	topLevel := 0
	for _, node := range entry.Credentials.AddressWithDelegates.Delegates {
		encoded, err := addressBytes(node.Address)
		if err != nil {
			t.Fatalf("encoding a delegate address: %v", err)
		}
		if bytes.Equal(encoded, targetEncoded) {
			topLevel++
		}
	}
	if topLevel != 1 {
		t.Errorf("the address appears %d times at the top level, want 1 there and 1 nested", topLevel)
	}

	signedEntry, err := AuthorizeEntry(context.Background(), entry,
		signerForLabel(t, step.SignerLabel),
		found.ValidUntilLedger, found.NetworkPassphrase, ForAddress(*step.ForAddress))
	if err != nil {
		t.Fatalf("the single signing step returned an unexpected error: %v", err)
	}

	total, nowSigned := countMatching(signedEntry)
	if total != 2 || nowSigned != 2 {
		t.Errorf("after one step, %d of %d nodes are signed; want 2 of 2", nowSigned, total)
	}
}
